"""Add espn_id to Owner

Revision ID: 4c4a001a1ab9
Revises: 5cde85f869d8
Create Date: 2023-12-06 13:15:04.630685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c4a001a1ab9'
down_revision = '5cde85f869d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('espn_id', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owner', schema=None) as batch_op:
        batch_op.drop_column('espn_id')

    # ### end Alembic commands ###
