"""Modified Schedule table with week_start field

Revision ID: 93c71f1f74cd
Revises: 0f8323647285
Create Date: 2023-12-20 11:20:33.528539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93c71f1f74cd'
down_revision = '0f8323647285'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('week_start', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_column('week_start')

    # ### end Alembic commands ###
