"""Deleted Game Model

Revision ID: a719a8aa18dc
Revises: 4c4a001a1ab9
Create Date: 2023-12-07 23:44:35.159401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a719a8aa18dc'
down_revision = '4c4a001a1ab9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('year', sa.INTEGER(), nullable=True),
    sa.Column('week', sa.INTEGER(), nullable=True),
    sa.Column('round', sa.INTEGER(), nullable=True),
    sa.Column('loser_team_id', sa.INTEGER(), nullable=True),
    sa.Column('winner_team_id', sa.INTEGER(), nullable=True),
    sa.Column('loser_score', sa.INTEGER(), nullable=True),
    sa.Column('winner_score', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['loser_team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['winner_team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
