"""Drop Game table

Revision ID: f60577fdc770
Revises: 1847152b3e6c
Create Date: 2023-12-13 13:11:43.244736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f60577fdc770'
down_revision = '1847152b3e6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('year', sa.INTEGER(), nullable=True),
    sa.Column('week', sa.INTEGER(), nullable=True),
    sa.Column('round', sa.INTEGER(), nullable=True),
    sa.Column('team1_id', sa.INTEGER(), nullable=True),
    sa.Column('team2_id', sa.INTEGER(), nullable=True),
    sa.Column('team1_score', sa.INTEGER(), nullable=True),
    sa.Column('team2_score', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('team1_seed', sa.INTEGER(), nullable=True),
    sa.Column('team2_seed', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['team1_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['team2_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
