"""Moved seeding from Team to Game

Revision ID: 4abf78506a96
Revises: eb56c53bef46
Create Date: 2023-12-13 10:03:41.466018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4abf78506a96'
down_revision = 'eb56c53bef46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team1_seed', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('team2_seed', sa.Integer(), nullable=True))

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_column('seed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seed', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('team2_seed')
        batch_op.drop_column('team1_seed')

    # ### end Alembic commands ###
