"""Added ESPN team_id to Team

Revision ID: eb56c53bef46
Revises: c484a988fd1c
Create Date: 2023-12-12 01:10:29.682918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb56c53bef46'
down_revision = 'c484a988fd1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('espn_team_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_column('espn_team_id')

    # ### end Alembic commands ###
